application: bryan-burgers
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: redirect.py
- url: /(resume|portfolio)
  script: redirect.py


- url: /resume/
  static_files: resume/index.html
  upload: resume/index.html

- url: /portfolio/
  static_files: portfolio/index.html
  upload: portfolio/index.html
- url: /portfolio/reportnet
  static_files: portfolio/reportnet.html
  upload: portfolio/reportnet.html
- url: /portfolio/images
  static_dir: portfolio/images

- url: /wedding/static
  static_dir: wedding/static
- url: /wedding/.*
  script: wedding/guests.py
  login: required
- url: /wedding
  script: wedding/guests.py

- url: /2009/frog-race/(.*)\.svg
  static_files: 2009/frog-race/\1.svg
  upload: 2009/frog-race/.*\.svg
  mime_type: image/svg+xml

- url: /2009/frog-race/(.*)\.manifest
  static_files: 2009/frog-race/\1.manifest
  upload: 2009/frog-race/.*\.manifest
  mime_type: text/cache-manifest
  
- url: /2009/frog-race
  static_dir: 2009/frog-race

- url: /2010/slide-rule/(.*)
  static_files: 2010/slide-rule/\1.svg
  upload: 2010/slide-rule/.*\.svg
  mime_type: image/svg+xml

- url: /2010/grades
  script: 2010/grades/grades.py

- url: /2010/train/test.svg
  static_files: 2010/train/test.svg
  upload: 2010/train/test.svg
  mime_type: image/svg+xml
- url: /2010/train/test.html
  static_files: 2010/train/test.html
  upload: 2010/train/test.html
  mime_type: text/html

- url: /2010/train/(.*)\.js
  static_files: 2010/train/\1.js
  upload: 2010/train/.*\.js
  mime_type: text/javascript

- url: /2011/android
  static_dir: 2011/android

# VITAMINS
- url: /2010/vitamins/cache.manifest
  static_files: 2010/vitamins/cache.manifest
  upload: 2010/vitamins/cache.manifest
  mime_type: text/cache-manifest
- url: /2010/vitamins/vitamins.html
  static_files: 2010/vitamins/vitamins.html
  upload: 2010/vitamins/vitamins.html
- url: /2010/vitamins/vitamins.css
  static_files: 2010/vitamins/vitamins.css
  upload: 2010/vitamins/vitamins.css
- url: /2010/vitamins/vitamins.js
  static_files: 2010/vitamins/vitamins.js
  upload: 2010/vitamins/vitamins.js
- url: /2010/vitamins/check.png
  static_files: 2010/vitamins/check.png
  upload: 2010/vitamins/check.png
- url: /2010/vitamins/vitamins-icon.png
  static_files: 2010/vitamins/vitamins-icon.png
  upload: 2010/vitamins/vitamins-icon.png
- url: /2010/vitamins/vitamins-splash.png
  static_files: 2010/vitamins/vitamins-splash.png
  upload: 2010/vitamins/vitamins-splash.png
- url: /2010/vitamins/check.svg
  static_files: 2010/vitamins/check.svg
  upload: 2010/vitamins/check.svg
  mime_type: image/svg+xml

# QUOTES
- url: /quotes/static
  static_dir: quotes/static
- url: /quotes/.*
  script: quotes/quotes.py
  login: admin
- url: /quotes
  script: quotes/quotes.py
  login: admin

- url: /id/bryan
  script: foaf.py
- url: /data/bryan
  script: foaf.py
- url: /profile/bryan
  script: foaf.py

# DATES
- url: /dates/static
  static_dir: dates/static
- url: /date/.*
  script: dates/dates.py
- url: /dates/.*
  script: dates/dates.py
- url: /dates(\..*)?
  script: dates/dates.py

# NOTE JAR
- url: /notes/data.json
  script: note-jar/notes.py
- url: /notes(/.*)?
  script: note-jar/notes.py

- url: /users
  script: foaf.py

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/bot/.*
  script: bots.py
- url: /_ah/xmpp/.*
  script: bots.py


inbound_services:
- xmpp_message
