application: bryan-burgers
version: 1
runtime: python
api_version: 1

handlers:
- url: /wedding/static
  static_dir: wedding/static
- url: /wedding/.*
  script: wedding/guests.py
  login: required
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

